
from websocketcall import startbot
# list_of_tickers = ['DGBUSDT', '1INCHUSDT','OPUSDT', 'DEFIUSDT', 'ANKRUSDT', 'KNCUSDT', 'BTCDOMUSDT', 'HOTUSDT', 'ZILUSDT', 'LTCUSDT', 'BATUSDT', 
# 'REEFUSDT', 'ONTUSDT', 'TRBUSDT', 'BELUSDT', 'GMTUSDT', 'ATOMUSDT', 'RENUSDT', 'ADAUSDT', 'LRCUSDT', 'DOGEUSDT', 'SOLUSDT', 'DOTUSDT', 'NKNUSDT', 'STMXUSDT', 'XEMUSDT',
# 'BNXUSDT', 'DUSKUSDT', 'ICXUSDT', 'SUSHIUSDT', 'DASHUSDT', 'IOTAUSDT', 'IOSTUSDT', 'MKRUSDT', 'WAVESUSDT', 'TLMUSDT', 'CRVUSDT', 'EOSUSDT', 
# 'DARUSDT', 'KLAYUSDT', 'NEARUSDT', 'ZENUSDT', 'LINKUSDT', 'WOOUSDT', 'FLOWUSDT', 'UNFIUSDT', 'BANDUSDT', 'ANTUSDT', 'TRXUSDT', 'DENTUSDT', 
# 'RSRUSDT', 'EGLDUSDT', 'GALUSDT', 'C98USDT', 'SANDUSDT', 'ALPHAUSDT', 'MANAUSDT', 'GTCUSDT', 'MATICUSDT', 'XMRUSDT', 'ALICEUSDT',
# 'OMGUSDT', 'IOTXUSDT', 'ROSEUSDT', 'KAVAUSDT', 'CELOUSDT', 'BTCUSDT', 'AAVEUSDT', 'ONEUSDT', 'ALGOUSDT', 'COMPUSDT', 'YFIUSDT', 'XRPUSDT', 'GRTUSDT',
# 'BNBUSDT','ARPAUSDT', 'RVNUSDT','ATAUSDT', 'VETUSDT', 'SXPUSDT', 'CHRUSDT', 'ZRXUSDT', 'IMXUSDT', 'LPTUSDT', 'DYDXUSDT',
# 'BTSUSDT', 'ARUSDT', 'MASKUSDT', 'LITUSDT', 'CTSIUSDT', 'SKLUSDT', '1000XECUSDT', 'MTLUSDT', 'BLZUSDT','HBARUSDT', 'COTIUSDT', 'KSMUSDT',
# 'PEOPLEUSDT', 'HNTUSDT','API3USDT','QTUMUSDT', 'BAKEUSDT', 'FILUSDT', 'OCEANUSDT', 'FTMUSDT', 'NEOUSDT', 'SNXUSDT', 'RLCUSDT', 
# 'AUDIOUSDT', 'THETAUSDT','CVCUSDT', 'CELRUSDT', 'STORJUSDT', 'FLMUSDT', 'APEUSDT', 'ETHUSDT', 'ZECUSDT', 'SFPUSDT', 'UNIUSDT', 'ENJUSDT', 'GALAUSDT', 
# 'ETCUSDT', 'CTKUSDT', 'XTZUSDT', 'FTTUSDT', 'SCUSDT', '1000SHIBUSDT', 'RAYUSDT', 'RUNEUSDT', 'XLMUSDT', 'ENSUSDT', 'JASMYUSDT', 'SRMUSDT', 'LINAUSDT', 
# 'CHZUSDT','BALUSDT', 'OGNUSDT', 'AXSUSDT', 'AVAXUSDT', 'TOMOUSDT', 'BCHUSDT']



# demo of how the function works

# list_of_tickers = ['ETHUSDT']
# timef = 1
# rr = 2
# tradesize= 10
# strategy = 'candleclose'
# risk_percentage=1
# startbot(timef, tradesize, rr, list_of_tickers,strategy, risk_percentage) 