# Generated by Django 4.0.6 on 2022-07-23 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_plan', models.TextField(default='BASIC')),
                ('expiration', models.DateField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscription',
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan', models.TextField()),
                ('created', models.DateTimeField()),
                ('expiry', models.DateTimeField()),
                ('currency', models.TextField()),
                ('network', models.TextField()),
                ('timePeriod', models.TextField()),
                ('transactionId', models.TextField()),
                ('verified', models.BooleanField()),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.subscription')),
            ],
        ),
    ]
