# Generated by Django 4.0.6 on 2022-07-23 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionhistory',
            old_name='subscription',
            new_name='current_subscription',
        ),
    ]
