# Generated by Django 4.0.2 on 2022-07-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_rename_subscription_transactionhistory_current_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='current_plan',
            field=models.TextField(default='basic'),
        ),
    ]
