# Generated by Django 4.0.2 on 2022-06-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=50, null=True)),
                ('apikey', models.CharField(max_length=100, unique=True)),
                ('apisecret', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
