# Generated by Django 4.0.2 on 2022-06-18 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='apikey',
        ),
        migrations.RemoveField(
            model_name='users',
            name='apisecret',
        ),
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
    ]
