# Generated by Django 4.0.2 on 2022-06-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_users_apikey_remove_users_apisecret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='apikey',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='apisecret',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default=False, max_length=32),
        ),
    ]
