# Generated by Django 4.0.2 on 2022-07-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_users_apikey_users_apisecret_users_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
