# Generated by Django 4.0.2 on 2022-07-08 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('risk', models.FloatField(default=1.0)),
                ('positionsize', models.IntegerField(default=10)),
                ('noticker', models.IntegerField(default=1)),
                ('strategy', models.CharField(default='rsi', max_length=5)),
                ('timeframe', models.IntegerField(default=30)),
                ('rrratio', models.FloatField(default=1.5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'preferances',
            },
        ),
    ]
