# Generated by Django 4.0.2 on 2022-06-21 13:30

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preferances',
            fields=[
                ('id', models.AutoField(auto_created=sqlalchemy.sql.expression.true, primary_key=True, serialize=False)),
                ('risk', models.FloatField()),
                ('positionsize', models.IntegerField()),
                ('noticker', models.IntegerField()),
                ('strategy', models.CharField(max_length=5)),
                ('timeframe', models.IntegerField()),
                ('rrratio', models.FloatField()),
            ],
            options={
                'db_table': 'preferances',
            },
        ),
    ]
