# Generated by Django 4.0.6 on 2022-07-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferances',
            name='strategy',
            field=models.CharField(default='rsi', max_length=15),
        ),
    ]
